CREATE OR REPLACE STREAM "RAW_ANOMALY_STREAM" (
   "favoritecaptain" VARCHAR(32),
   "rating"          INTEGER,
   "ANOMALY_SCORE"   DOUBLE);

CREATE OR REPLACE PUMP "RAW_PUMP" AS INSERT INTO "RAW_ANOMALY_STREAM"
SELECT STREAM "favoritecaptain", "rating", "ANOMALY_SCORE" FROM
TABLE(RANDOM_CUT_FOREST(
  CURSOR(SELECT STREAM "favoritecaptain", "rating" FROM "SOURCE_SQL_STREAM_001")
));

CREATE OR REPLACE STREAM "ORDERED_ANOMALY_STREAM" (
   "favoritecaptain" VARCHAR(32),
   "rating"          INTEGER,
   "ANOMALY_SCORE"   DOUBLE);

-- Sort records by descending anomaly score, insert into output stream
CREATE OR REPLACE PUMP "ORDERED_PUMP" AS INSERT INTO "ORDERED_ANOMALY_STREAM"
SELECT STREAM * FROM "RAW_ANOMALY_STREAM"
ORDER BY FLOOR("RAW_ANOMALY_STREAM".ROWTIME TO SECOND), "ANOMALY_SCORE" DESC;
